---
- name: Add New VM to HAProxy Backend
  hosts: all
  become: yes

  vars:
    haproxy_config_path: "/etc/haproxy/haproxy.cfg"
    server_name: "server-{{ backend_name | replace('_servers_', '-') }}-{{ new_vm_ip | replace('.', '-') }}" 

  tasks:
    - name: Add the new server to the specified HAProxy backend
      ansible.builtin.lineinfile:
        path: "{{ haproxy_config_path }}"
        regexp: '^\s*server\s+{{ server_name }}'
        insertafter: "^backend\\s+{{ backend_name }}$"
        line: "    server {{ server_name }} {{ new_vm_ip }}:{{ app_port }} check"
        state: present
        validate: "/usr/sbin/haproxy -c -f %s"
      register: haproxy_update

    - name: Reload HAProxy service to apply changes
      ansible.builtin.systemd:
        name: haproxy
        state: reloaded
      when: haproxy_update.changed