name: Deploy App-3 To-Do

on:
  push:
    branches:
      - dev
      - qa
      - prod
      
  # Seleção do ambiente em caso de trigger manual
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Selecione o ambiente para deploy manual (dev, qa, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - DEV
          - QA
          - PROD

# Variáveis de Ambiente GLOBAIS
# Estas variáveis estarão disponíveis em TODOS os jobs (terraform-* e destroy-*)
env:
  TF_VAR_vsphere_server: ${{ secrets.VSPHERE_SERVER }}
  TF_VAR_vsphere_user: ${{ secrets.VSPHERE_USER }}
  TF_VAR_vsphere_password: ${{ secrets.VSPHERE_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_DEFAULT_REGION: us-east-1
  TF_IN_AUTOMATION: true

jobs:
  terraform-dev:
    # Roda apenas em push para a branch 'dev'
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.target_environment == 'DEV')
    runs-on: self-hosted
    outputs:
      new_vm_ip: ${{ steps.get-ip.outputs.new_vm_ip }}
    environment:
      name: DEV

    # O bloco 'env' foi removido aqui, pois as variáveis Terraform/AWS são globais.

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Init
        id: init
        run: /usr/local/bin/terraform init
        working-directory: ./terraform/dev

      - name: Terraform Plan
        id: plan
        run: /usr/local/bin/terraform plan -input=false -out=tfplan
        working-directory: ./terraform/dev
        continue-on-error: true
        
      - name: Terraform Apply
        if: steps.plan.outcome == 'success'
        run: /usr/local/bin/terraform apply -auto-approve tfplan
        working-directory: ./terraform/dev

      - name: Get VM IP and Set as Output
        id: get-ip
        run: echo "new_vm_ip=$(/usr/local/bin/terraform output -raw new_vm_ip)" >> $GITHUB_OUTPUT
        working-directory: ./terraform/dev
        
      - name: Wait for VM to boot and SSH to be ready
        run: sleep 150 
  
  configure-vm-dev:
    runs-on: self-hosted
    needs: [terraform-dev]
    if: always() && needs.terraform-dev.result == 'success'
    environment:
      name: DEV
      # URL para ser visualizada no GHA
      url: http://${{ needs.terraform-dev.outputs.new_vm_ip }}:5000
      
    # Variáveis de Conexão do Ansible movidas para o nível do JOB
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"
      ANSIBLE_USER: "dev"
      ANSIBLE_CONNECTION: "ssh"
      ANSIBLE_CONNECT_TIMEOUT: "30"
      ANSIBLE_TIMEOUT: "60"
      ANSIBLE_BECOME: "true"

    steps:
      - name: Checkout Repository (Para o Playbook Ansible e arquivos)
        uses: actions/checkout@v4
      
      - name: Prepare SSH Key for Ansible
        run: |
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > /tmp/ansible_key
          chmod 600 /tmp/ansible_key
      
      - name: DEBUG - List files expected by Ansible
        run: |
          echo "Current directory is: $(pwd)"
          echo "Listing content of: files/"
          ls -la files/
          echo "Listing content of: ansible/"
          ls -la ansible/
        continue-on-error: true # Não deixe que isso falhe o job    
      
      - name: Run Ansible Playbook to Setup Flask
        # Usando as variáveis globais do Ansible definidas no 'env' do job
        run: ansible-playbook -i ${{ needs.terraform-dev.outputs.new_vm_ip }}, ansible/playbook.yml --user ${{ env.ANSIBLE_USER }} --private-key /tmp/ansible_key


#####################################################################
# JOB PARA PROVISIONAMENTO E CONFIGURAÇÃO DE QA
#####################################################################
  terraform-qa:
    # Roda apenas em push para a branch QA ou se selecionado manualmente como QA
    if: github.ref == 'refs/heads/qa' && github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.target_environment == 'QA')
    
    runs-on: self-hosted
    environment:
      name: QA
      
    # O bloco 'env' foi removido aqui, pois as variáveis Terraform/AWS são globais.

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Init (QA)
        run: /usr/local/bin/terraform init
        working-directory: ./terraform/qa

      - name: Terraform Apply (QA)
        run: /usr/local/bin/terraform apply -auto-approve
        working-directory: ./terraform/qa

      - name: Get VM IP and Set as Output (QA)
        id: get-ip-qa
        run: echo "new_vm_ip_qa=$(/usr/local/bin/terraform output -raw new_vm_ip)" >> $GITHUB_OUTPUT
        working-directory: ./terraform/qa
        
      - name: Wait for VM to boot and SSH to be ready
        run: sleep 120

    outputs:
      new_vm_ip_qa: ${{ steps.get-ip-qa.outputs.new_vm_ip_qa }}
      
  configure-vm-qa:
    runs-on: self-hosted
    needs: [terraform-qa] # Depende do provisionamento do QA
    if: always() && needs.terraform-qa.result == 'success'
    environment:
      name: QA
      url: http://${{ needs.terraform-qa.outputs.new_vm_ip_qa }}:5000
    
    # Variáveis de Conexão do Ansible movidas para o nível do JOB
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"
      ANSIBLE_USER: "dev" # Assumindo que o usuário SSH para QA também é 'dev'
      ANSIBLE_CONNECTION: "ssh"
      ANSIBLE_CONNECT_TIMEOUT: "30"
      ANSIBLE_TIMEOUT: "60"
      ANSIBLE_BECOME: "true"
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Prepare SSH Key for Ansible
        run: |
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > /tmp/ansible_key
          chmod 600 /tmp/ansible_key
          
      - name: Run Ansible Playbook to Setup Flask (QA)
        run: ansible-playbook -i ${{ needs.terraform-qa.outputs.new_vm_ip_qa }}, ansible/playbook.yml --user ${{ env.ANSIBLE_USER }} --private-key /tmp/ansible_key

#####################################################################
# JOB: DESTRUIR AMBIENTE DEV APÓS SUCESSO NO QA
#####################################################################
  destroy-dev-after-qa:
    runs-on: self-hosted
    needs: [configure-vm-qa]
    # Roda APENAS se a configuração do QA foi um sucesso E o trigger foi um push/manual para QA/PROD.
    if: success() && (github.ref == 'refs/heads/qa' || github.event.inputs.target_environment == 'PROD' || github.ref == 'refs/heads/prod') 
    
    # O bloco 'env' foi removido aqui, pois as variáveis Terraform/AWS são globais.

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Init (DEV Destroy)
        run: /usr/local/bin/terraform init
        working-directory: ./terraform/dev

      - name: Terraform Plan Destroy (DEBUG)
        run: /usr/local/bin/terraform plan -destroy
        working-directory: ./terraform/dev

      - name: Terraform Destroy (DEV)
        run: /usr/local/bin/terraform destroy -auto-approve
        working-directory: ./terraform/dev

#####################################################################
  # NOVO JOB: PROVISIONAMENTO AWS PROD (Terraform)
#####################################################################
  terraform-prod:
    runs-on: ubuntu-latest
    # Roda em push para 'prod' OU se selecionado manualmente como 'prod'.
    if: github.ref == 'refs/heads/prod' && github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.target_environment == 'PROD')
    
    environment:
      name: PROD
      # URL de produção.
      url: http://${{ steps.get-alb-dns.outputs.alb_dns }}
    
    outputs:
      alb_dns: ${{ steps.get-alb-dns.outputs.alb_dns }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Instala o Terraform no runner
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          # Define a versão do Terraform que você deseja usar (ex: 1.8.x)
          terraform_version: 1.8.0 

      - name: Terraform Init (PROD AWS)
        id: init
        # Agora o comando é apenas 'terraform init'
        run: terraform init
        working-directory: ./terraform/prod

      - name: Terraform Apply (PROD AWS)
        # Agora o comando é apenas 'terraform apply'
        run: terraform apply -auto-approve
        working-directory: ./terraform/prod

      - name: Get ALB DNS Name
        id: get-alb-dns
        # Agora o comando é apenas 'terraform output'
        run: echo "alb_dns=$(terraform output -raw alb_dns_name)" >> $GITHUB_OUTPUT
        working-directory: ./terraform/prod

#####################################################################
# JOB: DESTRUIR AMBIENTE QA APÓS SUCESSO NO PROD
#####################################################################
  destroy-qa-after-prod:
    runs-on: self-hosted
    needs: [terraform-prod]
    # Inclui o push para 'prod' e o trigger manual
    if: success() && (github.ref == 'refs/heads/prod' || github.event.inputs.target_environment == 'PROD') 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Init (QA Destroy)
        run: /usr/local/bin/terraform init
        working-directory: ./terraform/qa

      - name: Terraform Plan Destroy (DEBUG)
        run: /usr/local/bin/terraform plan -destroy
        working-directory: ./terraform/qa

      - name: Terraform Destroy (QA)
        run: /usr/local/bin/terraform destroy -auto-approve
        working-directory: ./terraform/qa
